CT1-CT7 failure: collateral transfered out from bucket should never be larger than bucket collateral (#759)
* Add unit test for CT1-CT7 failure

  Error: a >= b not satisfied [uint]
    Value a: 1200553203896460071992180228
    Value b: 1200553203896460071993273178

* When remove max collateral always make sure amount transfered out is not greater than collateral in bucket

* Revert "When remove max collateral always make sure amount transfered out is not greater than collateral in bucket"

This reverts commit aefe63ff3d7749ee45cd7f54c25e5f935895acc2.

* When remove max collateral always make sure amount transfered out is not greater than collateral in bucket

* Set no of buckets to 10 for regression test